# See
# - https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# - https://docs.github.com/en/actions/learn-github-actions/contexts
# - https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
name: Experimental images

on:
  # Rebuild every quarter on Sunday at 8:20 UTC
  schedule:
    - cron: 20 8 * 1/3 0

  # Build on push to master
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-experimental.yaml
      - "*.dockerfile"
      - files/**

concurrency:
  group: build-experimental-images
  cancel-in-progress: true

# Run the automated tests first, then publish the images if the tests pass
jobs:
  test:
    name: ${{ matrix.dockerfile }}
    uses: ./.github/workflows/test-job.yaml
    with:
      dockerfile: ${{ matrix.dockerfile }}
    strategy:
      fail-fast: true
      matrix:
        dockerfile:
          - apache
          - nginx

  apache:
    name: Apache
    needs: test
    uses: ./.github/workflows/build-job.yaml
    with:
      dockerfile: apache.dockerfile
      image-version: experimental
      tags: |
        ghcr.io/${{ github.repository_owner }}/baikal:experimental-apache
        ghcr.io/${{ github.repository_owner }}/baikal:experimental
    secrets: inherit

  nginx:
    name: Nginx
    needs: test
    uses: ./.github/workflows/build-job.yaml
    with:
      dockerfile: nginx.dockerfile
      image-version: experimental
      tags: ghcr.io/${{ github.repository_owner }}/baikal:experimental-nginx
    secrets: inherit
