name: Build job
on:
  workflow_call:
    inputs:
      dockerfile:
        description: Path to the Dockerfile to build
        required: true
        type: string
      tags:
        description: Tags to apply to the image
        required: true
        type: string
      image-version:
        description: Value for org.opencontainers.image.version label
        required: true
        type: string
      image-revision:
        description: Value for org.opencontainers.image.revision label
        default: ${{ github.sha }}
        type: string
      ref:
        description: Git reference to build
        default: ${{ github.ref }}
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          show-progress: false

      # See https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # See https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # See https://github.com/docker/login-action
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # See https://github.com/docker/build-push-action
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          file: ${{ inputs.dockerfile }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64/v8,linux/386
          push: true
          tags: ${{ inputs.tags }}
          labels: |
            org.opencontainers.image.created=${{ github.event.created_at }}
            org.opencontainers.image.url=https://ghcr.io/${{ github.repository_owner }}/baikal
            org.opencontainers.image.documentation=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ inputs.image-version }}
            org.opencontainers.image.revision=${{ inputs.image-revision }}
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.title=Baikal
            org.opencontainers.image.description=Ready-to-go Baikal server
