# See
# - https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
# - https://docs.github.com/en/actions/learn-github-actions/contexts
# - https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
name: Build release images

on:
  release:
    types:
      - published

concurrency:
  group: build-release-images
  cancel-in-progress: true

jobs:
  parse_release_tag:
    runs-on: ubuntu-latest
    outputs:
      baikal-version: ${{ steps.parse-release-tag.outputs.BAIKAL_VERSION }}
    steps:
      # Get the release version by stripping build metadata from the release name
      - name: Parse release tag
        id: parse-release-tag
        run: echo BAIKAL_VERSION=${GITHUB_REF_NAME/+*/} >> "$GITHUB_OUTPUT"

  nginx:
    name: Nginx
    needs: parse_release_tag
    uses: ./.github/workflows/build-job.yaml
    with:
      dockerfile: nginx.dockerfile
      image-version: ${{ needs.parse_release_tag.outputs.baikal-version }}
      tags: |
        ghcr.io/${{ github.repository_owner }}/baikal:${{ needs.parse_release_tag.outputs.baikal-version }}-nginx
        ghcr.io/${{ github.repository_owner }}/baikal:${{ needs.parse_release_tag.outputs.baikal-version }}
    secrets: inherit
